<link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}" type="text/css">
<link rel="stylesheet" href="{{ asset('css/font-awesome.css') }}" type="text/css">
<link rel="stylesheet" href="{{ asset('css/animate.css') }}" type="text/css">
<link rel="stylesheet" href="{{ asset('css/reset.css') }}" type="text/css">
<link rel="stylesheet" href="{{ asset('scss/style.css') }}" type="text/css">
<link rel="stylesheet" href="{{ asset('scss/media.css') }}" type="text/css">
<link rel="stylesheet" href="{{ asset('slick/slick.css') }}" type="text/css">
<link rel="stylesheet" href="{{ asset('css/select2.min.css') }}" type="text/css">
<link rel="stylesheet" href="{{ asset('jquery-ui/jquery-ui.css') }}" type="text/css">